//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EventSourcing.Background
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CAP_EventSourcingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CAP_EventSourcingEntities object using the connection string found in the 'CAP_EventSourcingEntities' section of the application configuration file.
        /// </summary>
        public CAP_EventSourcingEntities() : base("name=CAP_EventSourcingEntities", "CAP_EventSourcingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CAP_EventSourcingEntities object.
        /// </summary>
        public CAP_EventSourcingEntities(string connectionString) : base(connectionString, "CAP_EventSourcingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CAP_EventSourcingEntities object.
        /// </summary>
        public CAP_EventSourcingEntities(EntityConnection connection) : base(connection, "CAP_EventSourcingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccountBalance> AccountBalances
        {
            get
            {
                if ((_AccountBalances == null))
                {
                    _AccountBalances = base.CreateObjectSet<AccountBalance>("AccountBalances");
                }
                return _AccountBalances;
            }
        }
        private ObjectSet<AccountBalance> _AccountBalances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Current> Current
        {
            get
            {
                if ((_Current == null))
                {
                    _Current = base.CreateObjectSet<Current>("Current");
                }
                return _Current;
            }
        }
        private ObjectSet<Current> _Current;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transfer> Transfers
        {
            get
            {
                if ((_Transfers == null))
                {
                    _Transfers = base.CreateObjectSet<Transfer>("Transfers");
                }
                return _Transfers;
            }
        }
        private ObjectSet<Transfer> _Transfers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccountBalances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccountBalances(AccountBalance accountBalance)
        {
            base.AddObject("AccountBalances", accountBalance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Current EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurrent(Current current)
        {
            base.AddObject("Current", current);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transfers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransfers(Transfer transfer)
        {
            base.AddObject("Transfers", transfer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CAP_EventSourcingModel", Name="AccountBalance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccountBalance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccountBalance object.
        /// </summary>
        /// <param name="account">Initial value of the Account property.</param>
        /// <param name="dateOfBusiness">Initial value of the DateOfBusiness property.</param>
        /// <param name="balance">Initial value of the Balance property.</param>
        public static AccountBalance CreateAccountBalance(global::System.String account, global::System.DateTime dateOfBusiness, global::System.Decimal balance)
        {
            AccountBalance accountBalance = new AccountBalance();
            accountBalance.Account = account;
            accountBalance.DateOfBusiness = dateOfBusiness;
            accountBalance.Balance = balance;
            return accountBalance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                if (_Account != value)
                {
                    OnAccountChanging(value);
                    ReportPropertyChanging("Account");
                    _Account = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Account");
                    OnAccountChanged();
                }
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBusiness
        {
            get
            {
                return _DateOfBusiness;
            }
            set
            {
                if (_DateOfBusiness != value)
                {
                    OnDateOfBusinessChanging(value);
                    ReportPropertyChanging("DateOfBusiness");
                    _DateOfBusiness = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateOfBusiness");
                    OnDateOfBusinessChanged();
                }
            }
        }
        private global::System.DateTime _DateOfBusiness;
        partial void OnDateOfBusinessChanging(global::System.DateTime value);
        partial void OnDateOfBusinessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                OnBalanceChanging(value);
                ReportPropertyChanging("Balance");
                _Balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Balance");
                OnBalanceChanged();
            }
        }
        private global::System.Decimal _Balance;
        partial void OnBalanceChanging(global::System.Decimal value);
        partial void OnBalanceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CAP_EventSourcingModel", Name="Current")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Current : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Current object.
        /// </summary>
        /// <param name="dateOfBusiness">Initial value of the DateOfBusiness property.</param>
        public static Current CreateCurrent(global::System.DateTime dateOfBusiness)
        {
            Current current = new Current();
            current.DateOfBusiness = dateOfBusiness;
            return current;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBusiness
        {
            get
            {
                return _DateOfBusiness;
            }
            set
            {
                if (_DateOfBusiness != value)
                {
                    OnDateOfBusinessChanging(value);
                    ReportPropertyChanging("DateOfBusiness");
                    _DateOfBusiness = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateOfBusiness");
                    OnDateOfBusinessChanged();
                }
            }
        }
        private global::System.DateTime _DateOfBusiness;
        partial void OnDateOfBusinessChanging(global::System.DateTime value);
        partial void OnDateOfBusinessChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CAP_EventSourcingModel", Name="Transfer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transfer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transfer object.
        /// </summary>
        /// <param name="transferID">Initial value of the TransferID property.</param>
        /// <param name="from">Initial value of the From property.</param>
        /// <param name="to">Initial value of the To property.</param>
        /// <param name="dateOfBusiness">Initial value of the DateOfBusiness property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static Transfer CreateTransfer(global::System.Int32 transferID, global::System.String from, global::System.String to, global::System.DateTime dateOfBusiness, global::System.Decimal amount)
        {
            Transfer transfer = new Transfer();
            transfer.TransferID = transferID;
            transfer.From = from;
            transfer.To = to;
            transfer.DateOfBusiness = dateOfBusiness;
            transfer.Amount = amount;
            return transfer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransferID
        {
            get
            {
                return _TransferID;
            }
            set
            {
                if (_TransferID != value)
                {
                    OnTransferIDChanging(value);
                    ReportPropertyChanging("TransferID");
                    _TransferID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransferID");
                    OnTransferIDChanged();
                }
            }
        }
        private global::System.Int32 _TransferID;
        partial void OnTransferIDChanging(global::System.Int32 value);
        partial void OnTransferIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBusiness
        {
            get
            {
                return _DateOfBusiness;
            }
            set
            {
                OnDateOfBusinessChanging(value);
                ReportPropertyChanging("DateOfBusiness");
                _DateOfBusiness = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBusiness");
                OnDateOfBusinessChanged();
            }
        }
        private global::System.DateTime _DateOfBusiness;
        partial void OnDateOfBusinessChanging(global::System.DateTime value);
        partial void OnDateOfBusinessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();

        #endregion
    
    }

    #endregion
    
}
